# Generated by Django 2.0.3 on 2019-03-08 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incarceration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_date', models.DateField()),
                ('date_incarcerated', models.DateField()),
                ('date_bail_set', models.DateField()),
                ('date_of_jail_interview', models.DateField()),
                ('bail_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('docket_number', models.IntegerField()),
                ('date_support_call_completed', models.DateField()),
                ('notes', models.CharField(max_length=255)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Facility')),
                ('support_caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Person')),
                ('phone_number', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('notes', models.CharField(max_length=255)),
            ],
            bases=('core.person',),
        ),
        migrations.CreateModel(
            name='IncarceratedPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Person')),
                ('pronoun', models.CharField(blank=True, choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('MS', 'Ms'), ('MISS', 'Miss')], max_length=4)),
                ('race', models.CharField(choices=[('AFRICAN-AMERICAN', 'African-American'), ('HISPANIC', 'Hispanic'), ('ASIAN', 'Asian'), ('CAUCASIAN', 'Caucasian')], max_length=4)),
                ('date_of_birth', models.DateField(blank=True)),
                ('open_to_speaking_to_the_press', models.BooleanField(default=False)),
                ('ok_with_being_photographed', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=25)),
            ],
            bases=('core.person',),
        ),
        migrations.AddField(
            model_name='incarceration',
            name='contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='core.Contact'),
        ),
        migrations.AddField(
            model_name='incarceration',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.IncarceratedPerson'),
        ),
        migrations.AddField(
            model_name='incarceration',
            name='referred_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='core.Contact'),
        ),
    ]
