# Generated by Django 2.1.7 on 2019-03-18 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_date', models.DateField()),
                ('date_incarcerated', models.DateField()),
                ('date_bail_set', models.DateField()),
                ('date_of_jail_interview', models.DateField()),
                ('bail_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('docket_number', models.IntegerField()),
                ('date_support_call_completed', models.DateField()),
                ('support_funding_source', models.CharField(blank=True, max_length=255)),
                ('opt_in_for_additional_resources', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=25)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Person')),
                ('pronoun', models.CharField(blank=True, choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('MS', 'Ms'), ('MISS', 'Miss')], max_length=4)),
                ('race', multiselectfield.db.fields.MultiSelectField(choices=[('AFRICAN AMERICAN', 'African American'), ('AMERICAN INDIAN', 'American Indian'), ('ASIAN', 'Asian'), ('HISPANIC OR LATINO', 'Hispanic or Latino'), ('NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER', 'Native Hawaiian or Other Pacific Islander'), ('WHITE', 'White')], max_length=105)),
                ('date_of_birth', models.DateField(blank=True)),
                ('open_to_speaking_to_the_press', models.BooleanField(default=False)),
                ('ok_with_being_photographed', models.BooleanField(default=False)),
            ],
            bases=('core.person',),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Person')),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('core.person',),
        ),
        migrations.AddField(
            model_name='case',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Facility'),
        ),
        migrations.AddField(
            model_name='case',
            name='support_caller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='core.Contact'),
        ),
        migrations.AddField(
            model_name='case',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client'),
        ),
        migrations.AddField(
            model_name='case',
            name='referred_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='core.Contact'),
        ),
    ]
